import csv


school_dict = {
"Arizona State" : "﻿ASU", 
"ASU" : "ASU", "Arizona State " : "﻿ASU", "Arizona State Barney & Sil" : "﻿ASU", "Arizona State Brisson & " : "﻿ASU", 
"Arizona State C" : "﻿ASU", "Arizona State Canarie & Reve" : "﻿ASU", "Arizona State Canarie & Whee" : "﻿ASU", "Arizona State Chotras & Ra" : "﻿ASU", "Arizona State Chowdhury & K" : "﻿ASU", 
"Arizona State Ferdowsian & Vin" : "﻿ASU", "Arizona State Green & Red" : "﻿ASU", "Arizona State Guthrie & Ferdows" : "﻿ASU", "Arizona State Moe & Yo" : "﻿ASU", "Arizona State Quint & " : "﻿ASU", 
"Arizona State R" : "﻿ASU", "Arizona State Rajan & Chot" : "﻿ASU", 
"App State" : "App State", "AppSta" : "App State", "AppState" : "App State", "Appalachian State" : "App State", 
"Arizona Competitive Speech and Debate Club" : "Arizona Competitive Speech and Debate Club", "AriCom" : "Arizona Competitive Speech and Debate Club", 
"Arkansas" : "Arkansas", 
"AugCol" : "AugCol", "Auggie" : "AugCol", "Augie" : "AugCol", "Augsburg College" : "AugCol", 
"August" : "August", "Augustana" : "August", "Augustana - Engelhardt and Heid" : "August", "Augustana College" : "August", "Augustana College/Fresno State" : "August", 
"Bard" : "Bard", "Bard " : "Bard", "BarCol" : "Bard", 
"Baylor" : "Baylor", "Baylo" : "Baylor", "BayU" : "Baylor", "Baylor Alaina Walberg & Alden Con" : "Baylor", "Baylor Bacon & B" : "Baylor", 
"Baylor Barron & Con" : "Baylor", "Baylor Barron & Ev" : "Baylor", "Baylor Barron & Z" : "Baylor", "Baylor Boor  Bar" : "Baylor", "Baylor Evans & Chokh" : "Baylor", 
"Baylor Evans & Walb" : "Baylor", "Baylor Montgomery & St" : "Baylor", "Baylor Ramsey & Walms" : "Baylor", "Baylor Ramsey & Wil" : "Baylor", "Baylor Sheaff & Walb" : "Baylor", 
"Baylor Sheaff & Walms" : "Baylor", "Baylor Stump & Walms" : "Baylor", "Baylor Woods & Z" : "Baylor", 
"BC" : "BC", "Bos Col" : "BC", "BosCol" : "BC", "BosColl" : "BC", "Boston" : "BC", 
"Boston Coll" : "BC", "Boston College" : "BC", "Boston College - Ferguson and McCorm" : "BC", "Boston College Carelli & Kontopou" : "BC", "BostonColleg" : "BC", 
"Berkeley" : "Berkeley", "Cal" : "Berkeley", "CalBer" : "Berkeley", "CalBerkeley" : "Berkeley", "Cali" : "Berkeley", 
"California" : "Berkeley", "California Berkeley Wimsatt  SergentLevent" : "Berkeley", "California Berkeley" : "Berkeley", "California, Berkeley" : "Berkeley", "California, Berkeley Epner & Mar" : "Berkeley", 
"California, Berkeley Greenbury & Gru" : "Berkeley", "California, Berkeley Muppalla & Spurl" : "Berkeley", "California, Berkeley Sergent-Leventhal & Wims" : "Berkeley", "California, Berkeley Spurlock & Muppa" : "Berkeley", "UC Berke" : "Berkeley", 
"UC Berkeley" : "Berkeley", 
"BING" : "BING", "BHamt" : "BING", "BinU" : "BING", "Bing" : "BING", "Bingha" : "BING", 
"Bingha M" : "BING", "Bingham" : "BING", "Binghamton" : "BING", "Binghamton Buttgereit & Sm" : "BING", "Binghamton Cepin & Seh" : "BING", 
"Binghamton Friedman & Choudh" : "BING", "Binghamton Herrera & Ce" : "BING", "Binghamton Herrera & Sm" : "BING", "Binghamton Sehgal & Redd" : "BING", "Binghmtn" : "BING", 
"CSU Chico" : "CSU Chico", "CSUChi" : "CSU Chico", "CHICO" : "CSU Chico", "Chico" : "CSU Chico", 
"CSUF" : "CSUF", "CSUF Aquino & Soco" : "CSUF", "CSUFullerton" : "CSUF", "Cal State Fullerton" : "CSUF", "Cal State Fullerton Arias & Salc" : "CSUF", 
"Cal State Fullerton B" : "CSUF", "Cal State Fullerton Botello & R" : "CSUF", "Cal State Fullerton Brooks & Stanfi" : "CSUF", "Cal State Fullerton Delgado & Gonza" : "CSUF", "Cal State Fullerton Garcia & Ru" : "CSUF", 
"Cal State Fullerton Leon & Dela" : "CSUF", "Cal State Fullerton R" : "CSUF", "Cal State Fullerton Rawlings & R" : "CSUF", "Cal State Fullerton Rodriguez & Gonza" : "CSUF", "Cal State Fullerton Rosas & Ru" : "CSUF", 
"Cal State Fullerton Tero & Benc" : "CSUF", 
"CSU Long Beach" : "CSU Long Beach", "CSU Long Beach Broadway & Robe" : "CSU Long Beach", "CSULongBeach" : "CSU Long Beach", "Long Beach" : "CSU Long Beach", 
"California Maritime" : "California Maritime", 
"CSU - Northridge" : "CSU - Northridge", "CSU - Northridge Gevorgian & Taras" : "CSU - Northridge", "CSU - Northridge M" : "CSU - Northridge", "CSU Northridge" : "CSU - Northridge", "CSU-NR" : "CSU - Northridge", 
"CSUN" : "CSU - Northridge", "CSUN A" : "CSU - Northridge", "CSUN Bauer & Med" : "CSU - Northridge", "CSUN Gomez & Mel" : "CSU - Northridge", "CSUNor" : "CSU - Northridge", 
"Cal Poly" : "Cal Poly", "CalPol" : "Cal Poly", "CalPoly" : "Cal Poly", "CalPolySLO" : "Cal Poly", 
"CUNY" : "CUNY", "CUNY Ayaz  McInt" : "CUNY", "CUNY McIntyre & Jos" : "CUNY", 
"CenFla" : "CenFla", "CenFlo" : "CenFla", "CentFla" : "CenFla", "Central FL" : "CenFla", "Central Florida" : "CenFla", 
"UCF" : "CenFla", 
"CenOkl" : "CenOkl", "CenOkl George & Mel" : "CenOkl", "CenOkl Sewell & K" : "CenOkl", "Central Oklah" : "CenOkl", "Central Oklahoma" : "CenOkl", 
"Central Oklahoma Botkin & H" : "CenOkl", "Central Oklahoma Brenneman & Mo" : "CenOkl", "Central Oklahoma Colen & Colqu" : "CenOkl", "Central Oklahoma Flake & Mee" : "CenOkl", "Central Oklahoma Hamm & Hillig" : "CenOkl", 
"Central Oklahoma Hilligoss & Stid" : "CenOkl", "Central Oklahoma Karns & Mo" : "CenOkl", "Central Oklahoma Stidham & Whita" : "CenOkl", "Central Oklahoma Tyler Cauley & Logan Fl" : "CenOkl", 
"Chicago" : "Chicago", "Chicago Bahls & Palac" : "Chicago", 
"City College of San Francisco" : "City College of San Francisco", "CitCol" : "City College of San Francisco", 
"Clarion" : "Clarion", "ClaUni" : "Clarion", "ClaU" : "Clarion", "Clario" : "Clarion", "Clarion Camloh & Ba" : "Clarion", 
"Clarion Pierotti & Soren" : "Clarion", 
"Columbia" : "Columbia", 
"Concordia" : "Concordia", "ConCol" : "Concordia", "ConCol Clements & Pal" : "Concordia", "Concordia College" : "Concordia", "ConCol Clements & Shie" : "Concordia", 
"Concor" : "Concordia", "Concordia College Bosch & Snell" : "Concordia", "Concordia College Clements & Shie" : "Concordia", "Concordia College Shields & Snell" : "Concordia", "Concordia College Snelling & Bo" : "Concordia", 
"Concordia College Walker & Nes" : "Concordia", 
"Cornell" : "Cornell", "Cornel Mensah & S" : "Cornell", "Cornel Chang & " : "Cornell", "Cornel" : "Cornell", "Corne" : "Cornell", 
"Cornell K" : "Cornell", "Cornl" : "Cornell", 
"DC-CC" : "DC-CC", 
"Dartmouth" : "Dartmouth", "Dartm" : "Dartmouth", "Dart" : "Dartmouth", "DarCol Funston & Hill-W" : "Dartmouth", "Dartmo" : "Dartmouth", 
"Dartmouth College" : "Dartmouth", "Dartmouth College Belhachmi & Pac" : "Dartmouth", "Dartmouth College Ahmad & " : "Dartmouth", "Dartmouth College Chen & Cra" : "Dartmouth", "Dartmouth College C" : "Dartmouth", 
"Dartmouth S" : "Dartmouth", 
"Emory" : "Emory", "Em" : "Emory", "EmoUni" : "Emory", "Emory - Cambre and Holl" : "Emory", "Emory - Dean and Siga" : "Emory", 
"Emory A" : "Emory", "Emory Albert Liu & Miga " : "Emory", "Emory B" : "Emory", "Emory Ba" : "Emory", "Emory Baker & Yam" : "Emory", 
"Emory Bontha & D" : "Emory", "Emory Bu" : "Emory", "Emory Cheng & Saw" : "Emory", "Emory Dean & Klar" : "Emory", "Emory Fiero & H" : "Emory", 
"Emory Gross & Nel" : "Emory", "Emory Jones & Siga" : "Emory", "Emory Karthikeyan & Bon" : "Emory", "Emory Karthikeyan & Siga" : "Emory", "Emory Klarman & L" : "Emory", 
"Emory Marcus & Re" : "Emory", "Emory Rebecca Levy & Ilina Log" : "Emory", "Emory Sigalos & Karthike" : "Emory", "Emory Tucker & Morb" : "Emory", 
"Emporia State" : "Emporia State", "ESU" : "Emporia State", "EmpSt" : "Emporia State", "EmpSta" : "Emporia State", "EmpSta Gilmore & Huach" : "Emporia State", 
"Empor" : "Emporia State", "Emporia" : "Emporia State", "Emporia State Biswell & Bon" : "Emporia State", "Emporia State Isaach Johnson & Nick Wat" : "Emporia State", "Emporia State Lingenfelter & McGrana" : "Emporia State", 
"Emporia State Lucas Lord & Gage Simp" : "Emporia State", "Emporia State Monteith & Rick" : "Emporia State", "Emporia State Monteith & Wat" : "Emporia State", "Emporia State Rickard & Wa" : "Emporia State", "Emporia State Singleton & Warfi" : "Emporia State", 
"Florida" : "Florida", "Florid" : "Florida", "FLA" : "Florida", "Florid A" : "Florida", "Florid Allums & Ka" : "Florida", 
"Florid Allums & Scol" : "Florida", "Florid C" : "Florida", "Florid Callaghan & Kiz" : "Florida", "Florid Cartagena & Scol" : "Florida", "Florid Daskalakis & March" : "Florida", 
"Florida - Cartagena and " : "Florida", "Florida - Frank and Presc" : "Florida", "Florida - Krause and Vargh" : "Florida", "Florida Alexis & Shu" : "Florida", "Florida Allums & Scol" : "Florida", 
"Florida Callaghan & Kiz" : "Florida", "Florida Frank & Presc" : "Florida", "UFlori" : "Florida", 
"Florida State" : "Florida State", "FloridaSt" : "Florida State", "FloSta" : "Florida State", "FloSta Douglass & Go" : "Florida State", 
"Fresno State" : "Fresno State", "FRESNO" : "Fresno State", "FSU" : "Fresno State", "FSU M" : "Fresno State", "Fresno" : "Fresno State", 
"Fresno St" : "Fresno State", "FreSta" : "Fresno State", "Fresno State Holley & T" : "Fresno State", "Fresno State M" : "Fresno State", "Fresno State Lewis & Ah" : "Fresno State", 
"Fresno State Martinez & San" : "Fresno State", "Fresno State Mirza & L" : "Fresno State", "Fresno State Ratzlaff & Scriv" : "Fresno State", "Fresno State Vang & El" : "Fresno State", 
"Fullerton" : "Fullerton", "FullColl Abdullah & Majd-Far" : "Fullerton", "Fulle" : "Fullerton", "Fullerton Abdullah & Herrera-Gar" : "Fullerton", "Fullerton Gamboa & Mar" : "Fullerton", 
"Fullerton Gilmartin & Go" : "Fullerton", "Fullerton Haga & W" : "Fullerton", "Fullerton Indy" : "Fullerton", "Fullerton Jensen & Pe" : "Fullerton", "Fullerton Kejejyan & Su" : "Fullerton", 
"Fullerton Union" : "Fullerton", 
"George Mason" : "George Mason", "GMU" : "George Mason", "GMU H" : "George Mason", "GeoMas" : "George Mason", "George Mason - Brown and Woodw" : "George Mason", 
"George Mason - Dailey and Moh" : "George Mason", "George Mason - Kwon and Lastov" : "George Mason", "George Mason - Mendoza and St" : "George Mason", "George Mason Brown & Han" : "George Mason", "George Mason C" : "George Mason", 
"George Mason Dailey & K" : "George Mason", "George Mason K" : "George Mason", "George Mason Kwon & Lastov" : "George Mason", "George Mason Oliver & Tho" : "George Mason", 
"George Washington" : "George Washington", "GWU" : "George Washington", "GW" : "George Washington", "GeoWas" : "George Washington", "GeoWash" : "George Washington", 
"George Washington Arsht & Stasa" : "George Washington", "George Wash" : "George Washington", "George Washington CO" : "George Washington", "George Washington Nelson & Sala" : "George Washington", "George Washington Stenn & Stasa" : "George Washington", 
"George Washington Trevett & To" : "George Washington", 
"Georgetown" : "Georgetown", "GTown" : "Georgetown", "GTown E" : "Georgetown", "Georgetown Arsht & Mark" : "Georgetown", "Georgetown Burdette & Lou" : "Georgetown", 
"Georgetown E" : "Georgetown", "Georgetown Erpenbach & Krish" : "Georgetown", "Georgetown Erpenbach & McGr" : "Georgetown", "Georgetown Kazteridis & K" : "Georgetown", "Georgetown Kazteridis & Unw" : "Georgetown", 
"Georgetown Lenart & Pa" : "Georgetown", "Georgetown Louvis & Mc" : "Georgetown", "Georgetown McCoy & Lou" : "Georgetown", "Georgetown S" : "Georgetown", "GeorgetownE" : "Georgetown", 
"Gtown" : "Georgetown", 
"Georgia" : "Georgia", "Georgia - Caplan and Galerst" : "Georgia", "Georgia - Feinberg and Hebb" : "Georgia", "Georgi" : "Georgia", "Georgi Mokhemar & Yon" : "Georgia", 
"Georgi Stupek & Yon" : "Georgia", "Georgia - Layton and Shan" : "Georgia", "Georgia Caplan & Shan" : "Georgia", "Georgia Davis & Galerst" : "Georgia", "Georgia Davis & Vene" : "Georgia", 
"Georgia Feinberg & Bo" : "Georgia", "Georgia Galerstein & Hebb" : "Georgia", "Georgia Hackman & Marsh" : "Georgia", "Georgia Hebbale & Kha" : "Georgia", "Georgia Herrera &" : "Georgia", 
"Georgia Hoover & Hender" : "Georgia", "Georgia Mahajan & Hi" : "Georgia", "Georgia Mokhemar & Yon" : "Georgia", "Geor" : "Georgia", "Georg" : "Georgia", 
"UGA" : "Georgia", 
"Georgia State" : "Georgia State", "GSU" : "Georgia State", "GeoSta" : "Georgia State", "GeoSta L" : "Georgia State", "Georgia St" : "Georgia State", 
"Georgia State - Floyd and Na" : "Georgia State", "Georgia State De La Huerta & Huss" : "Georgia State", "Georgia State Finch & Fl" : "Georgia State", "Georgia State Flint & Na" : "Georgia State", "Georgia State Nails  Stew" : "Georgia State", 
"Georgia State Nails & Stew" : "Georgia State", "GeorgiaState" : "Georgia State", 
"Georgia Tech" : "Georgia Tech", "GaTech" : "Georgia Tech", "GeoTec" : "Georgia Tech", 
"Gonzaga" : "Gonzaga", "Gonzag" : "Gonzaga", "Gonza" : "Gonzaga", "Gonz" : "Gonzaga", "Gonzaga Bauer & John" : "Gonzaga", 
"Gonzaga Clawson & John" : "Gonzaga", "Gonzaga Filpi & Orne" : "Gonzaga", "Gonzaga Johnson & Bas" : "Gonzaga", "Gonzaga Newton & Sk" : "Gonzaga", "Gonzaga Skoog & Weinha" : "Gonzaga", 
"Gonzaga Newton & Spra" : "Gonzaga", "Gonzaga Weinhardt & DeGiova" : "Gonzaga", 
"Harvard" : "Harvard", "Harv" : "Harvard", "Harvard Xu & Her" : "Harvard", "Harvard Taylor & Dimitrije" : "Harvard", "Harvard Suo & Bol" : "Harvard", 
"Harvard Narayan & Sanj" : "Harvard", "Harvard Kim & Sea" : "Harvard", "Harvard Herman & Dimitrije" : "Harvard", "Harvard Heller & " : "Harvard", "Harvard Dimitrijevic & Her" : "Harvard", 
"Harvard Bolman & " : "Harvard", "Harvard Banks & Neust" : "Harvard", "Harvard Asimow & Drecker-Wax" : "Harvard", 
"Houston" : "Houston", "Housto" : "Houston", "Houston Jennings & Jenni" : "Houston", "Houston Bockmon & Tr" : "Houston", "Houston Asgari-Tari & Bock" : "Houston", 
"Houston Alexander & Be" : "Houston", "Houston A" : "Houston", "Housto McKinley & Ba" : "Houston", "Housto Khan & Zh" : "Houston", "Housto Gutierrez & Tr" : "Houston", 
"Houston Lanning & Rajw" : "Houston", "Houston Love & Willi" : "Houston", "UHous" : "Houston", "UHoust" : "Houston", 
"Idaho State" : "Idaho State", "Idaho St" : "Idaho State", "Idaho" : "Idaho State", "IdahoSt" : "Idaho State", "IdahoState" : "Idaho State", 
"Idaho State Doty & Ivano" : "Idaho State", "ISU" : "Idaho State", 
"Illinois" : "Illinois", "Illino Akari & Car" : "Illinois", "Illino Hodgson & Corbri" : "Illinois", "Illino Shahriari & Herz" : "Illinois", "Illinois Shahriari & Hender" : "Illinois", 
"Illinois Pecher & Herz" : "Illinois", "Illinois Hills & Phill" : "Illinois", 
"Illinois College" : "Illinois College", "IL College" : "Illinois College", "IllCol" : "Illinois College", "IllCol Groh & Men" : "Illinois College", "IllCol Herzing & Pelc" : "Illinois College", 
"IllCol Phillips & Hi" : "Illinois College", 
"IllState" : "IllState", "IllSta" : "IllState", "IllSt" : "IllState", "Ill State" : "IllState", "Illinois State - Harris and Ogb" : "IllState", 
"IllinoisSt" : "IllState", 
"Indiana" : "Indiana", "Indian Tally & Gall" : "Indiana", "Indian Smale & Hoff" : "Indiana", "Indian Pulluru & Sl" : "Indiana", "Indian Novicoff & Ta" : "Indiana", 
"Indian Njuguna & Woo" : "Indiana", "Indian Njuguna & Kal" : "Indiana", "Indian Maroney &" : "Indiana", "Indian Little & Linco" : "Indiana", "Indian Hoffman & Fergu" : "Indiana", 
"Indian Dehmlow Dunne & Ta" : "Indiana", "Indian Dehmlow Dunne & Gall" : "Indiana", "Indian Bagan & Gu" : "Indiana", "Indian Aaronson & Sm" : "Indiana", "Indian Aaronson & Fergu" : "Indiana", 
"Indian" : "Indiana", "IndUni" : "Indiana", "Indiana Watkins & Pe" : "Indiana", "Indiana Sw" : "Indiana", "Indiana Smale & Pecu" : "Indiana", 
"Indiana Smale & Hoff" : "Indiana", "Indiana Smale & Fergu" : "Indiana", "Indiana Murphy & Pa" : "Indiana", "Indiana Hoffman & Fergu" : "Indiana", "Indiana Harry Aaronson & Nick Gall" : "Indiana", 
"Indiana Galbreath & Ta" : "Indiana", "Indiana Ferguson & Hoff" : "Indiana", "Indiana Ben Tally & Cameron Dehmlow Du" : "Indiana", "Indiana Aaronson & Fergu" : "Indiana", "Indiana - Peculis and " : "Indiana", 
"JV Indiana" : "Indiana", "NV Indiana" : "Indiana", 
"Iowa" : "Iowa", "IU" : "Iowa", "Iow" : "Iowa", "Iowa Roetlin & Wri" : "Iowa", "Iowa Phalen & Wri" : "Iowa", 
"Iowa Phalen & Jack" : "Iowa", "Iowa Oberto-Besso & Shea" : "Iowa", "Iowa Kimbrough & Liri" : "Iowa", "Iowa Kann & Hanc" : "Iowa", "Iowa Hancock & Shea" : "Iowa", 
"Iowa H" : "Iowa", "Iowa Ding & Hanc" : "Iowa", "Iowa Croat & K" : "Iowa", "Iowa Christophersen & Kimbro" : "Iowa", 
"Irvine" : "Irvine", 
"JCCC " : "JCCC ", "JCCCC" : "JCCC ", "JCCC" : "JCCC ", "111 JCCC" : "JCCC ", "JCounty" : "JCCC ", 
"JohCou Warren & Se" : "JCCC ", "JohCou Russell & Brower-Free" : "JCCC ", "JohCou Peat & Cunning" : "JCCC ", "JohCou Owen & Mo" : "JCCC ", "JohCou Georges & No" : "JCCC ", 
"JohCou Drake & Ir" : "JCCC ", "JohCou Domme & Gilles" : "JCCC ", "JohCou Babrakzai & Pettib" : "JCCC ", "JohCou" : "JCCC ", "JohCo" : "JCCC ", 
"Johnson County Community Ruder & Nierm" : "JCCC ", "Johnson County Community Gulley & Vaug" : "JCCC ", "Johnson County Community Esfandiary & Monc" : "JCCC ", "Johnson County Community Engelbert & Single" : "JCCC ", "Johnson County Community College Secor & War" : "JCCC ", 
"Johnson County Community College Moore & Dod" : "JCCC ", "Johnson County Community College Moncure & O" : "JCCC ", "Johnson County Community College Gillespie & Nat" : "JCCC ", "Johnson County Community College Gillespie & Maic" : "JCCC ", "Johnson County Community College Georges & Pettib" : "JCCC ", 
"Johnson County Community College Emerson & Russ" : "JCCC ", "Johnson County Community College Drake & DeSh" : "JCCC ", "Johnson County Community College Domme & Dr" : "JCCC ", "Johnson County Community College Brower-Freeman & Nat" : "JCCC ", "Johnson County Community College" : "JCCC ", 
"Johnson County Community Choong & K" : "JCCC ", "Johnson County Community" : "JCCC ", "Johnson County Community Sara Coble & Aamer Ud" : "JCCC ", 
"John Carroll" : "John Carroll", "JCU" : "John Carroll", "JohCar" : "John Carroll", "John Carroll - Massarelli and Stol" : "John Carroll", "John Carroll - Himmelright and Mitsc" : "John Carroll", 
"John Carroll - Dockery and Men" : "John Carroll", 
"JMU" : "JMU", "JMU M" : "JMU", "JamMad" : "JMU", "James Madison" : "JMU", "James Madison - McGrath and Mil" : "JMU", 
"James Madison Miller & L" : "JMU", "James Madison Bosley & Mil" : "JMU", "JamesMadison" : "JMU", 
"Kansas" : "Kansas", "Kan" : "Kansas", "KU" : "Kansas", "Kans" : "Kansas", "Kansas Carey & Kha" : "Kansas", 
"Kansas Carey & D" : "Kansas", "Kansas Campbell & Bir" : "Kansas", "Kansas C" : "Kansas", "Kansas Boyce & Gar" : "Kansas", "Kansas Bhatla & C" : "Kansas", 
"Kansas Bevens & Mil" : "Kansas", "Kansas B" : "Kansas", "Kansas Delph & Glassc" : "Kansas", "Kansas Duff & Gar" : "Kansas", "Kansas Duff & Nel" : "Kansas", 
"Kansas Foreman & " : "Kansas", "Kansas Fort & Atk" : "Kansas", "Kansas H" : "Kansas", "Kansas Hampton & R" : "Kansas", "Kansas Hampton & Robin" : "Kansas", 
"Kansas Harris & Wef" : "Kansas", "Kansas Hegna & Mar" : "Kansas", "Kansas Katz & R" : "Kansas", "Kansas Khatri & Ca" : "Kansas", "Kansas Khatri & Sch" : "Kansas", 
"Kansas Monaghan & Nel" : "Kansas", "Kansas Peck & " : "Kansas", "Kansas Peck & R" : "Kansas", "Kansas Robinson & B" : "Kansas", "Kansas Sosalla-Bahr & He" : "Kansas", 
"Kansas Wefald & Ma" : "Kansas", "Kansas Woodcock & Sch" : "Kansas", "UKans" : "Kansas", 
"Kansas State" : "Kansas State", "K-State" : "Kansas State", "K State" : "Kansas State", "KSU" : "Kansas State", "KState" : "Kansas State", 
"KSU EPAW" : "Kansas State", "Kan St" : "Kansas State", "KanSt" : "Kansas State", "KanSta McMillin-Beckman & Stid" : "Kansas State", "KanSta Karimi & Stebb" : "Kansas State", 
"KanSta Jackson & Rami" : "Kansas State", "KanSta" : "Kansas State", "Kansas St" : "Kansas State", "Kansas State Ford & Sm" : "Kansas State", "Kansas State K" : "Kansas State", 
"Kansas State Klucas & Sc" : "Kansas State", "Kansas State Leyba & Risovi-Hendrick" : "Kansas State", "Kansas State McMillin-Beckman & Rami" : "Kansas State", "Kansas State Penn & P" : "Kansas State", "Kansas State Ramirez & P" : "Kansas State", 
"Kansas State Rowe & Grif" : "Kansas State", "Kansas State Scott & Stid" : "Kansas State", 
"Kansas City Kansas CC" : "Kansas City Kansas CC", "KCKCC" : "Kansas City Kansas CC", "KCKCC " : "Kansas City Kansas CC", "KCKS" : "Kansas City Kansas CC", "KanCit Torres & Sm" : "Kansas City Kansas CC", 
"KanCit Joseph & Mi" : "Kansas City Kansas CC", "KanCit Gonzaba & Jos" : "Kansas City Kansas CC", "KanCit Casas & N" : "Kansas City Kansas CC", "KanCit" : "Kansas City Kansas CC", "KanCi" : "Kansas City Kansas CC", 
"Kansas City Kansas CC Casas & Gonz" : "Kansas City Kansas CC", "Kansas City Kansas CC Ford & Glanz" : "Kansas City Kansas CC", "Kansas City Kansas CC Glanzman & F" : "Kansas City Kansas CC", "Kansas City Kansas CC Gonzaba  Jos" : "Kansas City Kansas CC", "Kansas City Kansas CC Gonzaba & Ca" : "Kansas City Kansas CC", 
"Kansas City Kansas CC Nave  Ca" : "Kansas City Kansas CC", "Kansas City Kansas CC Nave & Jos" : "Kansas City Kansas CC", "Kansas City Kansas CC Torres & Sm" : "Kansas City Kansas CC", "Kansas City Kansas CC Willett & Willi" : "Kansas City Kansas CC", 
"Kentucky" : "Kentucky", "Kentu" : "Kentucky", "Kentuc" : "Kentucky", "Kentuc Baller & Ri" : "Kentucky", "Kentuc Hackman & Ri" : "Kentucky", 
"Kentuc Kendrick & Marti" : "Kentucky", "Kentuc Rivas & Bal" : "Kentucky", "Kentuc Sanchez & Lo" : "Kentucky", "Kentucky Hampton & Ro" : "Kentucky", "Kentucky Grasse & Ro" : "Kentucky", 
"Kentucky Grasse & Nopars" : "Kentucky", "Kentucky Geldof & Varga" : "Kentucky", 
"LA City College" : "LA City College", "LACC" : "LA City College", 
"Lakeland College" : "Lakeland College", "Lakeland" : "Lakeland College", "LakCol" : "Lakeland College", 
"LCSC" : "LCSC", "LCSC - Lewis Cl" : "LCSC", "LewClark" : "LCSC", 
"Liberty" : "Liberty", "Libert" : "Liberty", "Liber" : "Liberty", "LibUni" : "Liberty", "LibU" : "Liberty", 
"LIBER" : "Liberty", "Liberty - Apthorp and Larem" : "Liberty", "Liberty - Ayodeji and Bobb" : "Liberty", "Liberty - Calizo and Mur" : "Liberty", "Liberty - Chiri and Wal" : "Liberty", 
"Liberty - Cowden and Truji" : "Liberty", "Liberty - Edwards and Febri" : "Liberty", "Liberty - Edwards and Hilli" : "Liberty", "Liberty - Gardner and Lotspe" : "Liberty", "Liberty - Landrum and Siegr" : "Liberty", 
"Liberty Apthorp & Bridw" : "Liberty", "Liberty Apthorp & Mur" : "Liberty", "Liberty B" : "Liberty", "Liberty Bobbitt & Mur" : "Liberty", "Liberty C" : "Liberty", 
"Liberty Calizo & Schi" : "Liberty", "Liberty Chiri & Edwa" : "Liberty", "Liberty Crane & Schi" : "Liberty", "Liberty S" : "Liberty", 
"Lindenwood" : "Lindenwood", "Lindenwd" : "Lindenwood", "Linden Warma & John" : "Lindenwood", "Linden Ward & Tur" : "Lindenwood", "Linden Swinford & M" : "Lindenwood", 
"Linden Nave & Wi" : "Lindenwood", "Linden Mire & Swinf" : "Lindenwood", "Linden De Leon & VanKlu" : "Lindenwood", "Linden" : "Lindenwood", "Lindenwood Johnson & Wa" : "Lindenwood", 
"Lindenwood Ward & VanKlu" : "Lindenwood", "Lindenwood Grant & Sm" : "Lindenwood", "Lwood" : "Lindenwood", 
"Los Rios" : "Los Rios", "LosRios" : "Los Rios", "LosRio" : "Los Rios", 
"Louisville" : "Louisville", "Louisv Walker & Willi" : "Louisville", "Louisv Gordon & Thomp" : "Louisville", "Louisv" : "Louisville", "LVille" : "Louisville", 
"Louisville Barnett & Lattim" : "Louisville", "Louisville Hanserd & Re" : "Louisville", "Louisville Pope & Tolb" : "Louisville", "Lville" : "Louisville", 
"Macalester" : "Macalester", "MacCol" : "Macalester", "Macalester College Smith & Cha" : "Macalester", 
"MIT Policy Debate" : "MIT Policy Debate", 
"Marist" : "Marist", 
"Mary Washington" : "Mary Washington", "Mary Washingto" : "Mary Washington", "Mary Wash." : "Mary Washington", "Mary Wash" : "Mary Washington", "MarWas" : "Mary Washington", 
"Mary Washington - Lopez and Pach" : "Mary Washington", "Mary Washington - McCleary and McElhi" : "Mary Washington", "Mary Washington - Obolensky and Yo" : "Mary Washington", "Mary Washington McElhinny & Pach" : "Mary Washington", "Mary Washington Pacheco & McElhi" : "Mary Washington", 
"Mary Washington Stackhouse & Yo" : "Mary Washington", "MaryWash" : "Mary Washington", "MaryW" : "Mary Washington", "UMW" : "Mary Washington", 
"Miami" : "Miami", "Miami I" : "Miami", "Miami Loureiro & Silver" : "Miami", "UMiami" : "Miami", 
"Michigan" : "Michigan", "JV Michigan" : "Michigan", "Michigan Allen & Pap" : "Michigan", "Michigan Brian Roche & Jacob Shel" : "Michigan", "Michigan Hirn & Krak" : "Michigan", 
"Michigan Jacob Goldschlag & Caitlin Walr" : "Michigan", "Michigan Jonah Jacobs & Allison Pu" : "Michigan", "Michigan Keenan & Kel" : "Michigan", "Michigan Keenan & Pei" : "Michigan", "Michigan Keller & Kee" : "Michigan", 
"Michigan M" : "Michigan", "Michigan Meyers-Levy & Dono" : "Michigan", "Michigan Meyers-Levy & Jac" : "Michigan", "Michigan Morgan & Krak" : "Michigan", "Michig Zhu & Ungerlei" : "Michigan", 
"Michig Zhu & Sm" : "Michigan", "Michig Walrath & Goldsch" : "Michigan", "Michig Vance & L" : "Michigan", "Michig Smith & Mead" : "Michigan", "Michig Shah & Walr" : "Michigan", 
"Michig Roche & Shel" : "Michigan", "Michig Meyers-Levy & Dono" : "Michigan", "Michig McGraw & Wolf" : "Michigan", "Michig Love & Rog" : "Michigan", "Michig Keenan & Pei" : "Michigan", 
"Michig Goldschlag & Shel" : "Michigan", "Michig Franz & Tay" : "Michigan", "Michig" : "Michigan", "Michi" : "Michigan", "Mich" : "Michigan", 
"UMich" : "Michigan", "UMi-" : "Michigan", 
"Michigan State" : "Michigan State", "JV Michigan State" : "Michigan State", "Mich St" : "Michigan State", "MicSta Lewis & Oley" : "Michigan State", "MicSta Jones & Walking" : "Michigan State", 
"MicSta Grossman & Serr" : "Michigan State", "MicSta Campbell & W" : "Michigan State", "MicSta Campbell & Le" : "Michigan State", "MicSta Brown & Pep" : "Michigan State", "MicSta Brill & Br" : "Michigan State", 
"MicSta Adair & Scull" : "Michigan State", "MicSta" : "Michigan State", "MSU" : "Michigan State", "MicSta Rodriguez & Gross" : "Michigan State", "MicSta Runburg & Br" : "Michigan State", 
"MicSta Runburg & Walking" : "Michigan State", "MicSta Staats & Nier" : "Michigan State", "MicSta Walkington & Munsin" : "Michigan State", "Michigan St." : "Michigan State", "Michigan State Thur & Str" : "Michigan State", 
"Michigan State Strong & T" : "Michigan State", "Michigan State Ramesh & T" : "Michigan State", "Michigan State Munsinger & Walking" : "Michigan State", "Michigan State Lewis & Br" : "Michigan State", "Michigan State Lena Grossman & Ezra Serr" : "Michigan State", 
"Michigan State Lavelle & Munsin" : "Michigan State", "Michigan State Fagan & Nier" : "Michigan State", "Michigan State Caporal & Ze" : "Michigan State", "Michigan State Campbell & Hender" : "Michigan State", "Michigan State Butler & Str" : "Michigan State", 
"Michigan State Brown & Placi" : "Michigan State", "Michigan State Brill & Runb" : "Michigan State", "Michigan State Alex Brown & Lauren Pep" : "Michigan State", "Michigan State - Gannon and T" : "Michigan State", "Michigan State - Butler and Capo" : "Michigan State", 
"Minnesota" : "Minnesota", "Minne" : "Minnesota", "Minn" : "Minnesota", "Minnes Asirvatham & Koste" : "Minnesota", "Minnes" : "Minnesota", 
"Minnes Asirvatham & Leb" : "Minnesota", "Minnes Carlson & Samsun" : "Minnesota", "Minnes Dharmadhikari &" : "Minnesota", "Minnes Ferguson & Ja" : "Minnesota", "Minnes Kostelny & W" : "Minnesota", 
"Minnes Kostelny & Welb" : "Minnesota", "Minnes Kuoch & Tauring-Trax" : "Minnesota", "Minnes Milkert & Willi" : "Minnesota", "Minnes Overbey & She" : "Minnesota", "Minneosta" : "Minnesota", 
"Minnesota Asirvatham & Kl" : "Minnesota", "Minnesota Crunkilton & Ehrl" : "Minnesota", "Minnesota Ehrlich & Crunkil" : "Minnesota", "Minnesota Milkert & Willi" : "Minnesota", "Minnesota Overbey & Tauring-Trax" : "Minnesota", 
"Minnesota Schauer & Sadago" : "Minnesota", "Minnesota Williams & Witas" : "Minnesota", "UMinn" : "Minnesota", 
"Missouri - Kansas City" : "Missouri - Kansas City", "Missouri - Kansas City Cho & Jo" : "Missouri - Kansas City", "Missouri - Kansas City Ajisafe & Fis" : "Missouri - Kansas City", "Mis- Niermann & " : "Missouri - Kansas City", "Mis- Cuellar & Jo" : "Missouri - Kansas City", 
"Mis- Ajisafe & W" : "Missouri - Kansas City", "Mis-" : "Missouri - Kansas City", "Misso" : "Missouri - Kansas City", "Missouri  Kansas City Turner  Nierm" : "Missouri - Kansas City", "Missouri - Kansas City Jutt & Hauschi" : "Missouri - Kansas City", 
"Missouri - Kansas City Jutt & Sc" : "Missouri - Kansas City", "Missouri - Kansas City Michael Hauschildt & Parker Mitch" : "Missouri - Kansas City", "Missouri - Kansas City Mitchell & Kro" : "Missouri - Kansas City", "Missouri - Kansas City Schartz & Sc" : "Missouri - Kansas City", "Missouri - Kansas City Schartz & Will" : "Missouri - Kansas City", 
"UMKC" : "Missouri - Kansas City", 
"Missouri State" : "Missouri State", "Missouri St" : "Missouri State", "MOState" : "Missouri State", "MO State" : "Missouri State", "MisSt" : "Missouri State", 
"MisSta" : "Missouri State", "Missouri State Bess & Rumba" : "Missouri State", "Missouri State Brower-Freeman & Hama" : "Missouri State", "Missouri State Cole & Brower-Free" : "Missouri State", "Missouri State Cole & Ru" : "Missouri State", 
"Missouri State Dickerson & Ev" : "Missouri State", "Missouri State Hackett & Wi" : "Missouri State", "Missouri State Pouya Pars" : "Missouri State", "Missouri State Rabbitt & " : "Missouri State", "Missouri State Russo & Mil" : "Missouri State", 
"Missouri State Smith & Wi" : "Missouri State", "Missouri State West & Wi" : "Missouri State", "Mo State" : "Missouri State", "Mo" : "Missouri State", "MissouriStat" : "Missouri State", 
"MoState" : "Missouri State", 
"Monmouth" : "Monmouth", "MONU" : "Monmouth", "MONM" : "Monmouth", "Monmou K" : "Monmouth", "Monmou" : "Monmouth", 
"MonU" : "Monmouth", "Monmouth B" : "Monmouth", 
"NYU" : "NYU", "NYU Dellamore & DeJ" : "NYU", "NYU Dellamore & G" : "NYU", "NYU Itliong & Z" : "NYU", "NYU Zhan & Kuzme" : "NYU", 
"New York" : "NYU", "NewYor" : "NYU", 
"Navy" : "Navy", "NV Navy" : "Navy", "Navy - Cutner and Jamordee-Con" : "Navy", "Navy B" : "Navy", "Navy C" : "Navy", 
"Navy M" : "Navy", 
"New School" : "New School", "NS" : "New School", "New S" : "New School", "New" : "New School", "NewSch" : "New School", 
"NewSchool" : "New School", 
"Northern Iowa" : "Northern Iowa", "JV Northern Iowa" : "Northern Iowa", "NorIow" : "Northern Iowa", "NorIow Hites & S" : "Northern Iowa", "Northern Iowa Guffey & Mil" : "Northern Iowa", 
"Northern Iowa Kauble & R" : "Northern Iowa", "Northern Iowa Kuiper & Mil" : "Northern Iowa", "Northern Iowa Miller & R" : "Northern Iowa", "Northern Iowa Shew & Ev" : "Northern Iowa", "Northern Iowa Simonson & S" : "Northern Iowa", 
"NorthernIowa" : "Northern Iowa", "UNI" : "Northern Iowa", 
"North Texas" : "North Texas", "NortT" : "North Texas", "NorTex" : "North Texas", "NorTX" : "North Texas", "No. Texas" : "North Texas", 
"North Texas Abraha & Kramb" : "North Texas", "North Texas Carroll & San Mig" : "North Texas", "North Texas Carroll & Sauc" : "North Texas", "North Texas Kersch & Ander" : "North Texas", "North Texas Quinn & Sauc" : "North Texas", 
"North Texas Rowe & Pr" : "North Texas", "NorthTexas" : "North Texas", "NorthTx" : "North Texas", "UNT" : "North Texas", "UNoTe" : "North Texas", 
"UNoTex" : "North Texas", 
"Northwestern" : "Northwestern", "Northwest" : "Northwestern", "Northw Jankovsky & Yo" : "Northwestern", "Northw Callahan & Weide" : "Northwestern", "Northw" : "Northwestern", 
"NWstrn" : "Northwestern", "NWestern" : "Northwestern", "Northwestern - McCarty and " : "Northwestern", "Northwestern - Miles and Shak" : "Northwestern", "Northwestern Callahan & Es" : "Northwestern", 
"Northwestern Esman & Mc" : "Northwestern", "Northwestern Gabriel 'Jelly Beans' Jankovsky & Joe Weide" : "Northwestern", "Northwestern Hopkins & Sriniva" : "Northwestern", "Northwestern McCarty & " : "Northwestern", "Northwestern Miles & Vellayap" : "Northwestern", 
"Northwestern O'Brien & Shak" : "Northwestern", "Northwestern O'Brien & Wo" : "Northwestern", "Northwestern Vellayappan & Mi" : "Northwestern", "Nwstrn" : "Northwestern", "Nwest" : "Northwestern", 
"NotDam" : "NotDam", 
"Oklahoma" : "Oklahoma", "Oklaho Les" : "Oklahoma", "Oklaho Leo" : "Oklahoma", "Oklaho" : "Oklahoma", "Oklah" : "Oklahoma", 
"Okla" : "Oklahoma", "OU" : "Oklahoma", "Oklahoma Ard & Chi" : "Oklahoma", "Oklahoma C" : "Oklahoma", "Oklahoma Campbell & " : "Oklahoma", 
"Oklahoma Cherry & Ba" : "Oklahoma", "Oklahoma Cherry & Ya" : "Oklahoma", "Oklahoma Crawford & Schleic" : "Oklahoma", "Oklahoma Juarez & Sm" : "Oklahoma", "Oklahoma Juarez & Wh" : "Oklahoma", 
"Oklahoma Langel & W" : "Oklahoma", "Oklahoma Leonardi & Master" : "Oklahoma", "Oklahoma Massey & Ma" : "Oklahoma", "Oklahoma Musapeta & Hurt" : "Oklahoma", "Oklahoma P" : "Oklahoma", 
"Oklahoma Pickens & Sanc" : "Oklahoma", "Oklahoma Plange & Sebu" : "Oklahoma", "Oklahoma Pruitt & Wit" : "Oklahoma", "Oklahoma Robbins & Ya" : "Oklahoma", "Oklahoma Sanchez & Pick" : "Oklahoma", 
"Oklahoma Schexnayder & B" : "Oklahoma", "Oklahoma Sebunya & Pla" : "Oklahoma", "Oklahoma Smith & W" : "Oklahoma", "Oklahoma VanHeteren & Noll" : "Oklahoma", "Oklahoma Wall & Shel" : "Oklahoma", 
"Oklahoma Wyde & Schexnay" : "Oklahoma", 
"Oregon" : "Oregon", "Oregon Mallon & Schaf" : "Oregon", "Oregon Viales & Ged" : "Oregon", 
"Pepperdine" : "Pepperdine", "Pepper" : "Pepperdine", 
"Pittsburgh" : "Pittsburgh", "Pittsb" : "Pittsburgh", "Pitt" : "Pittsburgh", "Pittsburgh Budny & Rama" : "Pittsburgh", "Pittsburgh Budny & Woodf" : "Pittsburgh", 
"Pittsburgh Piekos & Chebr" : "Pittsburgh", 
"Puget Sound" : "Puget Sound", "Puget Sound Clare & Donne" : "Puget Sound", "Puget" : "Puget Sound", "PugSou" : "Puget Sound", "PugetSound" : "Puget Sound", 
"UPS" : "Puget Sound", 
"Richmond" : "Richmond", "Richm" : "Richmond", 
"Rochester" : "Rochester", "Roches B" : "Rochester", "Roches" : "Rochester", "Roche" : "Rochester", "Roch" : "Rochester", 
"ROCH" : "Rochester", "Rochester " : "Rochester", "URoche" : "Rochester", 
"Rutgers-Newark" : "Rutgers-Newark", "Rutgers" : "Rutgers-Newark", "Rutger" : "Rutgers-Newark", "Rutge" : "Rutgers-Newark", "RutU" : "Rutgers-Newark", 
"RUTG" : "Rutgers-Newark", "Rutgers-Newark Haughton & Staff" : "Rutgers-Newark", "Rutgers-Newark Murphy & N" : "Rutgers-Newark", "Rutgers-Newark Smith & Rand" : "Rutgers-Newark", "Rutgers-Newark Stafford & Carr" : "Rutgers-Newark", 
"Rutgers-Newark Stafford & Haugh" : "Rutgers-Newark", "Rutgers-Newark Williams & Mur" : "Rutgers-Newark", "RutgersNewark" : "Rutgers-Newark", 
"Sacramento State" : "Sacramento State", "SacState" : "Sacramento State", "SacSta" : "Sacramento State", "Sac State" : "Sacramento State", 
"Samford" : "Samford", "Samfor Windus & Davenp" : "Samford", "Samfor Davis & Stap" : "Samford", "Samfor Davis & Ben" : "Samford", "Samfor Davenport & Bro" : "Samford", 
"Samfor Broadnax & S" : "Samford", "Samfor" : "Samford", "SamUni" : "Samford", "SamU" : "Samford", "Samford - Carley and Tho" : "Samford", 
"Samford Kiarra Broadnax & Max Willin" : "Samford", 
"San Diego State" : "San Diego State", "SDSU" : "San Diego State", "SanDiego" : "San Diego State", 
"San Francisco" : "San Francisco", "SanFra" : "San Francisco", 
"San Francisco State" : "San Francisco State", "SFSU" : "San Francisco State", "San Francisco State Ba" : "San Francisco State", "San Francisco State Bak" : "San Francisco State", "San Francisco State Binley & Ca" : "San Francisco State", 
"SMU" : "SMU", "Southern Methodist" : "SMU", "SouMe" : "SMU", "Southern Methodist Boyd & Madat" : "SMU", "Southern Methodist Fitussi & Bol" : "SMU", 
"Southwestern" : "Southwestern", "Southwestern Berry & Pe" : "Southwestern", "Southwestern C" : "Southwestern", "Southwestern College" : "Southwestern", "SouCol " : "Southwestern", 
"SouCol" : "Southwestern", "Southwestern College Barreto & Elizarra" : "Southwestern", "Southwestern College Del Castillo & Doug" : "Southwestern", "Southwestern Cruz & Ber" : "Southwestern", "Southwestern Macias & Parm" : "Southwestern", 
"Stanford" : "Stanford", 
"SUNY Bro" : "SUNY Bro", 
"Texas" : "Texas", "Texas Blaker & Wilczyn" : "Texas", "Texas Bleiweiss & Pa" : "Texas", "Texas C" : "Texas", "Texas Chowdhury & Mal" : "Texas", 
"Texas Clarke & Stran" : "Texas", "Texas Fitz & Mak" : "Texas", "Texas Harun & Seg" : "Texas", "Texas Kilpatrick & Stran" : "Texas", "Texas Sahara Khan & Jasmine " : "Texas", 
"Texas Segura & Jo" : "Texas", "Texas Sen & Wa" : "Texas", "Texas Wilczynski & Mak" : "Texas", "UT-An" : "Texas", "UT-Ant" : "Texas", 
"Towson" : "Towson", "Towso" : "Towson", "Towson Begum & Good" : "Towson", "Towson Booker & Medei" : "Towson", "Towson Gillespie & Under" : "Towson", 
"Towson Johnson & Ruf" : "Towson", "Towson Thomas & Whit" : "Towson", "Towson University" : "Towson", 
"Trinity" : "Trinity", "TriU" : "Trinity", "Trinit" : "Trinity", "Trini" : "Trinity", "TriUni" : "Trinity", 
"Trinity Deshpande & Udaw" : "Trinity", "Trinity Dill & Khul" : "Trinity", "Trinity Ha & Mith" : "Trinity", "Trinity Rothenbaum & Sol" : "Trinity", "Trinity Udawala & Tor" : "Trinity", 
"Trinity Vail & Yo" : "Trinity", 
"UCO" : "CenOkl", "UCeOk" : "CenOkl", 
"UChicago" : "UChicago", 
"UDC-CC" : "UDC-CC", 
"USC" : "USC", "Southern California" : "USC", "Southern Califor" : "USC", "SouCal" : "USC", "Southern Cal" : "USC", 
"Southern California Berger & Lar" : "USC", "Southern California Haas & Saied" : "USC", "Southern California Purk & Vitzil" : "USC", "Southern California Nhan & Over" : "USC", 
"USF" : "USF", "South Florida" : "USF", "SoFlorida" : "USF", 
"UNLV" : "UNLV", "Nevada Las Vegas" : "UNLV", "Nevada Las Vegas Bhatti & Jall" : "UNLV", "Nevada Las Vegas Brooks & Stanfi" : "UNLV", "Nevada Las Vegas Gomez & Ve" : "UNLV", 
"Nevada Las Vegas Kezios & Og" : "UNLV", "Nevada Las Vegas Rodriguez & Ve" : "UNLV", "Nevada Las Vegas Saxe & Jall" : "UNLV", 
"UT Dallas" : "UT Dallas", "UT Dallas Aisha Bawany & Gabriel Sanc" : "UT Dallas", "UT Dallas B" : "UT Dallas", "UT Dallas Baez & K" : "UT Dallas", "UT Dallas Ballard & Flana" : "UT Dallas", 
"UT Dallas Becker & John" : "UT Dallas", "UT Dallas Gilbert & Ri" : "UT Dallas", "UT Dallas Kapoor & B" : "UT Dallas", "UT Dallas Ogbuli & Lo" : "UT Dallas", "UT Dallas Sanchez & Sanc" : "UT Dallas", 
"UT Dallas Vera & Do" : "UT Dallas", "UTD" : "UT Dallas", "UTDal" : "UT Dallas", "UTDallas" : "UT Dallas", 
"UT San Antonio" : "UT San Antonio", "UT San Antonio Alanis & Ok" : "UT San Antonio", "UT San Antonio Alegria & War" : "UT San Antonio", "UT San Antonio Nation & Pa" : "UT San Antonio", "UT San Antonio Pleitez & Mora" : "UT San Antonio", 
"UT San Antonio Rakestraw & Woep" : "UT San Antonio", "UTSA" : "UT San Antonio", "UTSan" : "UT San Antonio", "UTSan Colwell & Robert" : "UT San Antonio", "UTSan Gittens & Golds" : "UT San Antonio", 
"UTSan Elizondo & Gr" : "UT San Antonio", "UTSan Morales & Plei" : "UT San Antonio", "UTSanAntonio" : "UT San Antonio", 
"United States Military" : "United States Military", "UniSta" : "United States Military", "UniSta Caston & Min" : "United States Military", "UniSta H" : "United States Military", "UniSta O" : "United States Military", 
"United States Militar" : "United States Military", "United States Military Bryant & Bar" : "United States Military", "United States Military McGovern & Spi" : "United States Military", "Army" : "United States Military", "USMA" : "United States Military", 
"Utah State University Eastern" : "Utah State University Eastern", 
"Vanderbilt" : "Vanderbilt", "Vander Link &" : "Vanderbilt", "Vander Lin & " : "Vanderbilt", "Vander Kohlmaier & New" : "Vanderbilt", "Vander Kohlmaier & Co" : "Vanderbilt", 
"Vander James & Remi" : "Vanderbilt", "Vander" : "Vanderbilt", "VanU" : "Vanderbilt", "Vanderbilt - Bilgi and Mitch" : "Vanderbilt", "Vanderbilt - Carlos Calderon Gom and Pa" : "Vanderbilt", 
"Vanderbilt - Rehman and Z" : "Vanderbilt", "Vanderbilt - Stothers and Willif" : "Vanderbilt", "Vandy" : "Vanderbilt", "Vandy J" : "Vanderbilt", 
"Vermont" : "Vermont", "UVM" : "Vermont", "Vermon" : "Vermont", "Verm" : "Vermont", "Vermont Brough  " : "Vermont", 
"Vermt" : "Vermont", 
"Virgina Tech" : "Virgina Tech", "VA Tech" : "Virginia Tech",
"Wake Forest" : "Wake Forest", "Wake For" : "Wake Forest", "Wake " : "Wake Forest", "Wake" : "Wake Forest", "WakFor geraghty & Kl" : "Wake Forest", 
"WakFor Gonzalez & Shap" : "Wake Forest", "WakFor" : "Wake Forest", "Wake Forest - Bailey and " : "Wake Forest", "Wake Forest - Clifford and Vi" : "Wake Forest", "Wake Forest - Crowe and Le" : "Wake Forest", 
"Wake Forest - Duff and La" : "Wake Forest", "Wake Forest - Hurwitz and Qu" : "Wake Forest", "Wake Forest Duff & La" : "Wake Forest", "Wake Forest LeDuc & Washing" : "Wake Forest", "Wake Forest Lopez & McC" : "Wake Forest", 
"Wake Forest Min & Qu" : "Wake Forest", "Wake Forest Mitchell & S" : "Wake Forest", "Wake Forest Quinn & " : "Wake Forest", "Wake Forest Quinn & Hurw" : "Wake Forest", "Wake Forest S" : "Wake Forest", 
"Wake Forest Shaw & Manches" : "Wake Forest", "Wake Forest Stirrat & Vi" : "Wake Forest", "Wake Forest Sugino & Cro" : "Wake Forest", "WakeF" : "Wake Forest", "WakeForest" : "Wake Forest", 
"WashStLouis" : "WashStLouis", 
"Wash U" : "Wash U", "UW Kunsay  Tas" : "Wash U", "UW Fischer  " : "Wash U", "WasUni" : "Wash U", "WashU" : "Wash U", 
"Washington" : "Wash U", "Washto" : "Wash U", 
"Wayne State" : "Wayne State", "JV Wayne State" : "Wayne State", "Wayne St" : "Wayne State", "Wayne" : "Wayne State", "WaySta Matmanivong  Ibra" : "Wayne State", 
"WaySta Jancek & Reyno" : "Wayne State", "WaySta Haynes  Jayyo" : "Wayne State", "WaySta Haran & Ma" : "Wayne State", "WaySta Davis & Hu" : "Wayne State", "WaySta Curtiss & Hu" : "Wayne State", 
"WaySta Anton & Willi" : "Wayne State", "WaySta Anton & Da" : "Wayne State", "WaySta" : "Wayne State", "Wayne State - Black and Brund" : "Wayne State", "Wayne State - Brundage and Schim" : "Wayne State", 
"Wayne State - Collins and Dun" : "Wayne State", "Wayne State - Dodson and Na" : "Wayne State", "Wayne State - Justice and S" : "Wayne State", "Wayne State - Leap and Mess" : "Wayne State", "Wayne State Davis & Hu" : "Wayne State", 
"Wayne State Davis & R" : "Wayne State", "Wayne State Doug Husic & Kristina Curt" : "Wayne State", "Wayne State Husic & Ma" : "Wayne State", "Wayne State Justice & S" : "Wayne State", "Wayne State Katrail Davis & Jenny An" : "Wayne State", 
"Wayne State Nagel & S" : "Wayne State", "Wayne State Nagel & Wi" : "Wayne State", "WayneState" : "Wayne State", 
"Weber State" : "Weber State", "Weber St" : "Weber State", "Weber R" : "Weber State", "Weber" : "Weber State", "WebSta" : "Weber State", 
"Weber State Alvarado & Sha" : "Weber State", "Weber State Auro & Mug" : "Weber State", "Weber State Baker & Ra" : "Weber State", "Weber State Bergen & Hei" : "Weber State", "Weber State Butterfield & Sho" : "Weber State", 
"Weber State Chadwick & Sanc" : "Weber State", "Weber State Gaither & Mora" : "Weber State", "Weber State Gaither & Tipp" : "Weber State", "Weber State Greenwell & Wineh" : "Weber State", "Weber State Hall & Hens" : "Weber State", 
"Weber State Hall & Ra" : "Weber State", "Weber State Hall & Vee" : "Weber State", "Weber State Hendricks & Tipp" : "Weber State", "Weber State Hislop & Orq" : "Weber State", "Weber State Johnson & Steph" : "Weber State", 
"Weber State McPherson & Mounar" : "Weber State", "Weber State Olsen & Gait" : "Weber State", "Weber State Olsen & Vee" : "Weber State", "Weber State Raso & Wil" : "Weber State", "Weber State Soper & Shackelf" : "Weber State", 
"Weber State Thiede & Wil" : "Weber State", "WeberSt" : "Weber State", 
"West Conn" : "West Conn", "WCSU" : "West Conn", "WesCon" : "West Conn", "WestConn" : "West Conn", "WesternConn" : "West Conn", 
"West Georgia" : "West Georgia", "WesGeo" : "West Georgia", "WGC" : "West Georgia", "WGA" : "West Georgia", "West Ga" : "West Georgia", 
"West Georgia Ard & Muham" : "West Georgia", "West Georgia Gaius & Rob" : "West Georgia", "West Georgia Jordan & Tahmasi" : "West Georgia", "WestGa" : "West Georgia", "WestGA" : "West Georgia", 
"WestGeorgia" : "West Georgia", 
"West Virginia" : "West Virginia", "WVU" : "West Virginia", "WesVir" : "West Virginia", "West VA" : "West Virginia", "West Virginia - Orteza and Russ" : "West Virginia", 
"West Virginia Abe & Fi" : "West Virginia", "West Virginia Dorsey & Ejimo" : "West Virginia", "West Virginia Orteza & Russ" : "West Virginia", "West Virginia Pruden & Guirg" : "West Virginia", "WestVa" : "West Virginia", 
"WestVirginia" : "West Virginia", "Western Connecticut State" : "West Virginia", "Western Connect" : "West Virginia", 
"Western Washington" : "Western Washington", "Western Washington Johnson & Ste" : "Western Washington", 
"Whitman College" : "Whitman College", "Whitman" : "Whitman College", "Whit" : "Whitman College", "WhiCol" : "Whitman College", "Whitman College Anderson & Bar" : "Whitman College", 
"Whitman College Anderson & Newm" : "Whitman College", "Whitman College Durand & Mul" : "Whitman College", "Whitman College Hauck & Koch" : "Whitman College", "Whitman College Kochman & Thomp" : "Whitman College", "Whitman College Lassiter & Dur" : "Whitman College", 
"Whitman College Lassiter & Thomp" : "Whitman College", "Whitman College Menzies & Bar" : "Whitman College", 
"Wichita State" : "Wichita State", "Wichita St" : "Wichita State", "Wichita" : "Wichita State", "WicSta" : "Wichita State", "WicSt" : "Wichita State", 
"Wichita State Crane & We" : "Wichita State", "Wichita State Lefler & El" : "Wichita State", "Wichita State McCorkendale & " : "Wichita State", "Wichita State McFarland & O'Donn" : "Wichita State", "Wichita State Michelle Sherrow & Trinity We" : "Wichita State", 
"Wichita State O'Donnell & Saund" : "Wichita State", "Wichita State Saunders & We" : "Wichita State", "WichitaState" : "Wichita State", 
"Wilkes" : "Wilkes", "Wilke" : "Wilkes", "ASU" : "ASU",
"Wisconsin- Madison" : "Wisconsin- Madison", "WisMad" : "Wisconsin- Madison", 
"Wyoming" : "Wyoming", "Wyomin" : "Wyoming", "Wyoming Berry & Cul" : "Wyoming", "Wyoming Culver & Be" : "Wyoming", "Wyoming Dilldine & McFarl" : "Wyoming", 
"Wyoming Graziano & Jo" : "Wyoming", "Wyoming Henman & Thomson-Lic" : "Wyoming", "Wyoming Marcum & McFarl" : "Wyoming", "Wyoming Marcum & Pa" : "Wyoming", }


counting_dict = {'ASU Aff Wins' : 0, 'ASU Aff Total' : 0, 'ASU Neg Wins' : 0, 'ASU Neg Total' : 0, 'App State Aff Wins' : 0, 'App State Aff Total' : 0, 'App State Neg Wins' : 0, 'App State Neg Total' : 0, 
'Arizona Competitive Speech and Debate Club Aff Wins' : 0, 'Arizona Competitive Speech and Debate Club Aff Total' : 0, 'Arizona Competitive Speech and Debate Club Neg Wins' : 0, 'Arizona Competitive Speech and Debate Club Neg Total' : 0, 
'Arkansas Aff Wins' : 0, 'Arkansas Aff Total' : 0, 'Arkansas Neg Wins' : 0, 'Arkansas Neg Total' : 0, 
'AugCol Aff Wins' : 0, 'AugCol Aff Total' : 0, 'AugCol Neg Wins' : 0, 'AugCol Neg Total' : 0, 
'August Aff Wins' : 0, 'August Aff Total' : 0, 'August Neg Wins' : 0, 'August Neg Total' : 0, 
'Bard Aff Wins' : 0, 'Bard Aff Total' : 0, 'Bard Neg Wins' : 0, 'Bard Neg Total' : 0, 
'Baylor Aff Wins' : 0, 'Baylor Aff Total' : 0, 'Baylor Neg Wins' : 0, 'Baylor Neg Total' : 0, 
'BC Aff Wins' : 0, 'BC Aff Total' : 0, 'BC Neg Wins' : 0, 'BC Neg Total' : 0, 
'Berkeley Aff Wins' : 0, 'Berkeley Aff Total' : 0, 'Berkeley Neg Wins' : 0, 'Berkeley Neg Total' : 0, 
'BING Aff Wins' : 0, 'BING Aff Total' : 0, 'BING Neg Wins' : 0, 'BING Neg Total' : 0, 
'CSU Chico Aff Wins' : 0, 'CSU Chico Aff Total' : 0, 'CSU Chico Neg Wins' : 0, 'CSU Chico Neg Total' : 0, 
'CSUF Aff Wins' : 0, 'CSUF Aff Total' : 0, 'CSUF Neg Wins' : 0, 'CSUF Neg Total' : 0, 
'CSU Long Beach Aff Wins' : 0, 'CSU Long Beach Aff Total' : 0, 'CSU Long Beach Neg Wins' : 0, 'CSU Long Beach Neg Total' : 0, 
'California Maritime Aff Wins' : 0, 'California Maritime Aff Total' : 0, 'California Maritime Neg Wins' : 0, 'California Maritime Neg Total' : 0, 
'CSU - Northridge Aff Wins' : 0, 'CSU - Northridge Aff Total' : 0, 'CSU - Northridge Neg Wins' : 0, 'CSU - Northridge Neg Total' : 0, 
'Cal Poly Aff Wins' : 0, 'Cal Poly Aff Total' : 0, 'Cal Poly Neg Wins' : 0, 'Cal Poly Neg Total' : 0, 
'CUNY Aff Wins' : 0, 'CUNY Aff Total' : 0, 'CUNY Neg Wins' : 0, 'CUNY Neg Total' : 0, 
'CenFla Aff Wins' : 0, 'CenFla Aff Total' : 0, 'CenFla Neg Wins' : 0, 'CenFla Neg Total' : 0, 
'CenOkl Aff Wins' : 0, 'CenOkl Aff Total' : 0, 'CenOkl Neg Wins' : 0, 'CenOkl Neg Total' : 0, 
'Chicago Aff Wins' : 0, 'Chicago Aff Total' : 0, 'Chicago Neg Wins' : 0, 'Chicago Neg Total' : 0, 
'City College of San Francisco Aff Wins' : 0, 'City College of San Francisco Aff Total' : 0, 'City College of San Francisco Neg Wins' : 0, 'City College of San Francisco Neg Total' : 0, 
'Clarion Aff Wins' : 0, 'Clarion Aff Total' : 0, 'Clarion Neg Wins' : 0, 'Clarion Neg Total' : 0, 
'Columbia Aff Wins' : 0, 'Columbia Aff Total' : 0, 'Columbia Neg Wins' : 0, 'Columbia Neg Total' : 0, 
'Concordia Aff Wins' : 0, 'Concordia Aff Total' : 0, 'Concordia Neg Wins' : 0, 'Concordia Neg Total' : 0, 
'Cornell Aff Wins' : 0, 'Cornell Aff Total' : 0, 'Cornell Neg Wins' : 0, 'Cornell Neg Total' : 0, 
'DC-CC Aff Wins' : 0, 'DC-CC Aff Total' : 0, 'DC-CC Neg Wins' : 0, 'DC-CC Neg Total' : 0, 
'Dartmouth Aff Wins' : 0, 'Dartmouth Aff Total' : 0, 'Dartmouth Neg Wins' : 0, 'Dartmouth Neg Total' : 0, 
'Emory Aff Wins' : 0, 'Emory Aff Total' : 0, 'Emory Neg Wins' : 0, 'Emory Neg Total' : 0, 
'Emporia State Aff Wins' : 0, 'Emporia State Aff Total' : 0, 'Emporia State Neg Wins' : 0, 'Emporia State Neg Total' : 0, 
'Florida Aff Wins' : 0, 'Florida Aff Total' : 0, 'Florida Neg Wins' : 0, 'Florida Neg Total' : 0, 
'Florida State Aff Wins' : 0, 'Florida State Aff Total' : 0, 'Florida State Neg Wins' : 0, 'Florida State Neg Total' : 0, 
'Fresno State Aff Wins' : 0, 'Fresno State Aff Total' : 0, 'Fresno State Neg Wins' : 0, 'Fresno State Neg Total' : 0, 
'Fullerton Aff Wins' : 0, 'Fullerton Aff Total' : 0, 'Fullerton Neg Wins' : 0, 'Fullerton Neg Total' : 0, 
'George Mason Aff Wins' : 0, 'George Mason Aff Total' : 0, 'George Mason Neg Wins' : 0, 'George Mason Neg Total' : 0, 
'George Washington Aff Wins' : 0, 'George Washington Aff Total' : 0, 'George Washington Neg Wins' : 0, 'George Washington Neg Total' : 0, 
'Georgetown Aff Wins' : 0, 'Georgetown Aff Total' : 0, 'Georgetown Neg Wins' : 0, 'Georgetown Neg Total' : 0, 
'Georgia Aff Wins' : 0, 'Georgia Aff Total' : 0, 'Georgia Neg Wins' : 0, 'Georgia Neg Total' : 0, 
'Georgia State Aff Wins' : 0, 'Georgia State Aff Total' : 0, 'Georgia State Neg Wins' : 0, 'Georgia State Neg Total' : 0, 
'Georgia Tech Aff Wins' : 0, 'Georgia Tech Aff Total' : 0, 'Georgia Tech Neg Wins' : 0, 'Georgia Tech Neg Total' : 0, 
'Gonzaga Aff Wins' : 0, 'Gonzaga Aff Total' : 0, 'Gonzaga Neg Wins' : 0, 'Gonzaga Neg Total' : 0, 
'Harvard Aff Wins' : 0, 'Harvard Aff Total' : 0, 'Harvard Neg Wins' : 0, 'Harvard Neg Total' : 0, 
'Houston Aff Wins' : 0, 'Houston Aff Total' : 0, 'Houston Neg Wins' : 0, 'Houston Neg Total' : 0, 
'Idaho State Aff Wins' : 0, 'Idaho State Aff Total' : 0, 'Idaho State Neg Wins' : 0, 'Idaho State Neg Total' : 0, 
'Illinois Aff Wins' : 0, 'Illinois Aff Total' : 0, 'Illinois Neg Wins' : 0, 'Illinois Neg Total' : 0, 
'Illinois College Aff Wins' : 0, 'Illinois College Aff Total' : 0, 'Illinois College Neg Wins' : 0, 'Illinois College Neg Total' : 0, 
'IllState Aff Wins' : 0, 'IllState Aff Total' : 0, 'IllState Neg Wins' : 0, 'IllState Neg Total' : 0, 
'Indiana Aff Wins' : 0, 'Indiana Aff Total' : 0, 'Indiana Neg Wins' : 0, 'Indiana Neg Total' : 0, 
'Iowa Aff Wins' : 0, 'Iowa Aff Total' : 0, 'Iowa Neg Wins' : 0, 'Iowa Neg Total' : 0, 
'Irvine Aff Wins' : 0, 'Irvine Aff Total' : 0, 'Irvine Neg Wins' : 0, 'Irvine Neg Total' : 0, 
'JCCC  Aff Wins' : 0, 'JCCC  Aff Total' : 0, 'JCCC  Neg Wins' : 0, 'JCCC  Neg Total' : 0, 
'John Carroll Aff Wins' : 0, 'John Carroll Aff Total' : 0, 'John Carroll Neg Wins' : 0, 'John Carroll Neg Total' : 0, 
'JMU Aff Wins' : 0, 'JMU Aff Total' : 0, 'JMU Neg Wins' : 0, 'JMU Neg Total' : 0, 
'Kansas Aff Wins' : 0, 'Kansas Aff Total' : 0, 'Kansas Neg Wins' : 0, 'Kansas Neg Total' : 0, 
'Kansas State Aff Wins' : 0, 'Kansas State Aff Total' : 0, 'Kansas State Neg Wins' : 0, 'Kansas State Neg Total' : 0, 
'Kansas City Kansas CC Aff Wins' : 0, 'Kansas City Kansas CC Aff Total' : 0, 'Kansas City Kansas CC Neg Wins' : 0, 'Kansas City Kansas CC Neg Total' : 0, 
'Kentucky Aff Wins' : 0, 'Kentucky Aff Total' : 0, 'Kentucky Neg Wins' : 0, 'Kentucky Neg Total' : 0, 
'LA City College Aff Wins' : 0, 'LA City College Aff Total' : 0, 'LA City College Neg Wins' : 0, 'LA City College Neg Total' : 0, 
'Lakeland College Aff Wins' : 0, 'Lakeland College Aff Total' : 0, 'Lakeland College Neg Wins' : 0, 'Lakeland College Neg Total' : 0, 
'LCSC Aff Wins' : 0, 'LCSC Aff Total' : 0, 'LCSC Neg Wins' : 0, 'LCSC Neg Total' : 0, 
'Liberty Aff Wins' : 0, 'Liberty Aff Total' : 0, 'Liberty Neg Wins' : 0, 'Liberty Neg Total' : 0, 
'Lindenwood Aff Wins' : 0, 'Lindenwood Aff Total' : 0, 'Lindenwood Neg Wins' : 0, 'Lindenwood Neg Total' : 0, 
'Los Rios Aff Wins' : 0, 'Los Rios Aff Total' : 0, 'Los Rios Neg Wins' : 0, 'Los Rios Neg Total' : 0, 
'Louisville Aff Wins' : 0, 'Louisville Aff Total' : 0, 'Louisville Neg Wins' : 0, 'Louisville Neg Total' : 0, 
'Macalester Aff Wins' : 0, 'Macalester Aff Total' : 0, 'Macalester Neg Wins' : 0, 'Macalester Neg Total' : 0, 
'MIT Policy Debate Aff Wins' : 0, 'MIT Policy Debate Aff Total' : 0, 'MIT Policy Debate Neg Wins' : 0, 'MIT Policy Debate Neg Total' : 0, 
'Marist Aff Wins' : 0, 'Marist Aff Total' : 0, 'Marist Neg Wins' : 0, 'Marist Neg Total' : 0, 
'Mary Washington Aff Wins' : 0, 'Mary Washington Aff Total' : 0, 'Mary Washington Neg Wins' : 0, 'Mary Washington Neg Total' : 0, 
'Miami Aff Wins' : 0, 'Miami Aff Total' : 0, 'Miami Neg Wins' : 0, 'Miami Neg Total' : 0, 
'Michigan Aff Wins' : 0, 'Michigan Aff Total' : 0, 'Michigan Neg Wins' : 0, 'Michigan Neg Total' : 0, 
'Michigan State Aff Wins' : 0, 'Michigan State Aff Total' : 0, 'Michigan State Neg Wins' : 0, 'Michigan State Neg Total' : 0, 
'Minnesota Aff Wins' : 0, 'Minnesota Aff Total' : 0, 'Minnesota Neg Wins' : 0, 'Minnesota Neg Total' : 0, 
'Missouri - Kansas City Aff Wins' : 0, 'Missouri - Kansas City Aff Total' : 0, 'Missouri - Kansas City Neg Wins' : 0, 'Missouri - Kansas City Neg Total' : 0, 
'Missouri State Aff Wins' : 0, 'Missouri State Aff Total' : 0, 'Missouri State Neg Wins' : 0, 'Missouri State Neg Total' : 0, 
'Monmouth Aff Wins' : 0, 'Monmouth Aff Total' : 0, 'Monmouth Neg Wins' : 0, 'Monmouth Neg Total' : 0, 
'NYU Aff Wins' : 0, 'NYU Aff Total' : 0, 'NYU Neg Wins' : 0, 'NYU Neg Total' : 0, 
'Navy Aff Wins' : 0, 'Navy Aff Total' : 0, 'Navy Neg Wins' : 0, 'Navy Neg Total' : 0, 
'New School Aff Wins' : 0, 'New School Aff Total' : 0, 'New School Neg Wins' : 0, 'New School Neg Total' : 0, 
'Northern Iowa Aff Wins' : 0, 'Northern Iowa Aff Total' : 0, 'Northern Iowa Neg Wins' : 0, 'Northern Iowa Neg Total' : 0, 
'North Texas Aff Wins' : 0, 'North Texas Aff Total' : 0, 'North Texas Neg Wins' : 0, 'North Texas Neg Total' : 0, 
'Northwestern Aff Wins' : 0, 'Northwestern Aff Total' : 0, 'Northwestern Neg Wins' : 0, 'Northwestern Neg Total' : 0, 
'NotDam Aff Wins' : 0, 'NotDam Aff Total' : 0, 'NotDam Neg Wins' : 0, 'NotDam Neg Total' : 0, 
'Oklahoma Aff Wins' : 0, 'Oklahoma Aff Total' : 0, 'Oklahoma Neg Wins' : 0, 'Oklahoma Neg Total' : 0, 
'Oregon Aff Wins' : 0, 'Oregon Aff Total' : 0, 'Oregon Neg Wins' : 0, 'Oregon Neg Total' : 0, 
'Pepperdine Aff Wins' : 0, 'Pepperdine Aff Total' : 0, 'Pepperdine Neg Wins' : 0, 'Pepperdine Neg Total' : 0, 
'Pittsburgh Aff Wins' : 0, 'Pittsburgh Aff Total' : 0, 'Pittsburgh Neg Wins' : 0, 'Pittsburgh Neg Total' : 0, 
'Puget Sound Aff Wins' : 0, 'Puget Sound Aff Total' : 0, 'Puget Sound Neg Wins' : 0, 'Puget Sound Neg Total' : 0, 
'Richmond Aff Wins' : 0, 'Richmond Aff Total' : 0, 'Richmond Neg Wins' : 0, 'Richmond Neg Total' : 0, 
'Rochester Aff Wins' : 0, 'Rochester Aff Total' : 0, 'Rochester Neg Wins' : 0, 'Rochester Neg Total' : 0, 
'Rutgers-Newark Aff Wins' : 0, 'Rutgers-Newark Aff Total' : 0, 'Rutgers-Newark Neg Wins' : 0, 'Rutgers-Newark Neg Total' : 0, 
'Sacramento State Aff Wins' : 0, 'Sacramento State Aff Total' : 0, 'Sacramento State Neg Wins' : 0, 'Sacramento State Neg Total' : 0, 
'Samford Aff Wins' : 0, 'Samford Aff Total' : 0, 'Samford Neg Wins' : 0, 'Samford Neg Total' : 0, 
'San Diego State Aff Wins' : 0, 'San Diego State Aff Total' : 0, 'San Diego State Neg Wins' : 0, 'San Diego State Neg Total' : 0, 
'San Francisco Aff Wins' : 0, 'San Francisco Aff Total' : 0, 'San Francisco Neg Wins' : 0, 'San Francisco Neg Total' : 0, 
'San Francisco State Aff Wins' : 0, 'San Francisco State Aff Total' : 0, 'San Francisco State Neg Wins' : 0, 'San Francisco State Neg Total' : 0, 
'SMU Aff Wins' : 0, 'SMU Aff Total' : 0, 'SMU Neg Wins' : 0, 'SMU Neg Total' : 0, 
'Southwestern Aff Wins' : 0, 'Southwestern Aff Total' : 0, 'Southwestern Neg Wins' : 0, 'Southwestern Neg Total' : 0, 
'Stanford Aff Wins' : 0, 'Stanford Aff Total' : 0, 'Stanford Neg Wins' : 0, 'Stanford Neg Total' : 0, 
'SUNY Bro Aff Wins' : 0, 'SUNY Bro Aff Total' : 0, 'SUNY Bro Neg Wins' : 0, 'SUNY Bro Neg Total' : 0, 
'Texas Aff Wins' : 0, 'Texas Aff Total' : 0, 'Texas Neg Wins' : 0, 'Texas Neg Total' : 0, 
'Towson Aff Wins' : 0, 'Towson Aff Total' : 0, 'Towson Neg Wins' : 0, 'Towson Neg Total' : 0, 
'Trinity Aff Wins' : 0, 'Trinity Aff Total' : 0, 'Trinity Neg Wins' : 0, 'Trinity Neg Total' : 0, 
'UChicago Aff Wins' : 0, 'UChicago Aff Total' : 0, 'UChicago Neg Wins' : 0, 'UChicago Neg Total' : 0, 
'UDC-CC Aff Wins' : 0, 'UDC-CC Aff Total' : 0, 'UDC-CC Neg Wins' : 0, 'UDC-CC Neg Total' : 0, 
'USC Aff Wins' : 0, 'USC Aff Total' : 0, 'USC Neg Wins' : 0, 'USC Neg Total' : 0, 
'USF Aff Wins' : 0, 'USF Aff Total' : 0, 'USF Neg Wins' : 0, 'USF Neg Total' : 0, 
'UNLV Aff Wins' : 0, 'UNLV Aff Total' : 0, 'UNLV Neg Wins' : 0, 'UNLV Neg Total' : 0, 
'UT Dallas Aff Wins' : 0, 'UT Dallas Aff Total' : 0, 'UT Dallas Neg Wins' : 0, 'UT Dallas Neg Total' : 0, 
'UT San Antonio Aff Wins' : 0, 'UT San Antonio Aff Total' : 0, 'UT San Antonio Neg Wins' : 0, 'UT San Antonio Neg Total' : 0, 
'United States Military Aff Wins' : 0, 'United States Military Aff Total' : 0, 'United States Military Neg Wins' : 0, 'United States Military Neg Total' : 0, 
'Utah State University Eastern Aff Wins' : 0, 'Utah State University Eastern Aff Total' : 0, 'Utah State University Eastern Neg Wins' : 0, 'Utah State University Eastern Neg Total' : 0, 
'Vanderbilt Aff Wins' : 0, 'Vanderbilt Aff Total' : 0, 'Vanderbilt Neg Wins' : 0, 'Vanderbilt Neg Total' : 0, 
'Vermont Aff Wins' : 0, 'Vermont Aff Total' : 0, 'Vermont Neg Wins' : 0, 'Vermont Neg Total' : 0, 
'Virgina Tech Aff Wins' : 0, 'Virgina Tech Aff Total' : 0, 'Virgina Tech Neg Wins' : 0, 'Virgina Tech Neg Total' : 0, 
'Wake Forest Aff Wins' : 0, 'Wake Forest Aff Total' : 0, 'Wake Forest Neg Wins' : 0, 'Wake Forest Neg Total' : 0, 
'WashStLouis Aff Wins' : 0, 'WashStLouis Aff Total' : 0, 'WashStLouis Neg Wins' : 0, 'WashStLouis Neg Total' : 0, 
'Wash U Aff Wins' : 0, 'Wash U Aff Total' : 0, 'Wash U Neg Wins' : 0, 'Wash U Neg Total' : 0, 
'Wayne State Aff Wins' : 0, 'Wayne State Aff Total' : 0, 'Wayne State Neg Wins' : 0, 'Wayne State Neg Total' : 0, 
'Weber State Aff Wins' : 0, 'Weber State Aff Total' : 0, 'Weber State Neg Wins' : 0, 'Weber State Neg Total' : 0, 
'West Conn Aff Wins' : 0, 'West Conn Aff Total' : 0, 'West Conn Neg Wins' : 0, 'West Conn Neg Total' : 0, 
'West Georgia Aff Wins' : 0, 'West Georgia Aff Total' : 0, 'West Georgia Neg Wins' : 0, 'West Georgia Neg Total' : 0, 
'West Virginia Aff Wins' : 0, 'West Virginia Aff Total' : 0, 'West Virginia Neg Wins' : 0, 'West Virginia Neg Total' : 0, 
'Western Washington Aff Wins' : 0, 'Western Washington Aff Total' : 0, 'Western Washington Neg Wins' : 0, 'Western Washington Neg Total' : 0, 
'Whitman College Aff Wins' : 0, 'Whitman College Aff Total' : 0, 'Whitman College Neg Wins' : 0, 'Whitman College Neg Total' : 0, 
'Wichita State Aff Wins' : 0, 'Wichita State Aff Total' : 0, 'Wichita State Neg Wins' : 0, 'Wichita State Neg Total' : 0, 
'Wilkes Aff Wins' : 0, 'Wilkes Aff Total' : 0, 'Wilkes Neg Wins' : 0, 'Wilkes Neg Total' : 0, 
'Wisconsin- Madison Aff Wins' : 0, 'Wisconsin- Madison Aff Total' : 0, 'Wisconsin- Madison Neg Wins' : 0, 'Wisconsin- Madison Neg Total' : 0, 
'Wyoming Aff Wins' : 0, 'Wyoming Aff Total' : 0, 'Wyoming Neg Wins' : 0, 'Wyoming Neg Total' : 0, 
'Aff Wins' : 0, 'Aff Total' : 0, 'Neg Wins' : 0,  'Neg Total' : 0 }

ignore_list = [ r"﻿104 Drury", r"105 Sterling", r"117 Crowder", r"4WBeg", r"4WCS", r"4WSo", r"6WAdv", r"6WInt", r"ADV", r"ASU/Wyomin", r"ASU\ISU", r"ASU\PugetSound", r"Airline", r"Albuquerque", r"Alpharetta", r"Alpharetta HS", r"Altam", r"Anoka", r"Arizona State/SDSU", r"Arizona State/Wyoming", r"Asian Debate League", r"Atholton", r"Augsburg/UC Berkeley", r"Austin SFA", r"BK", r"Baltimore City", r"Bard College/San Diego State", r"Bard\SDSU", r"Barsto", r"Barstow", r"Beacon", r"Beckman", r"Bellarmine", r"Bellarmine CP", r"Bellarmine College Prep", r"BerPre", r"Berkeley Prep", r"Berkeley Preparatory", r"Berklyn Prepnical Independent", r"Berkner", r"BingRoc", r"Bing\WVU", r"Bingha\Wilkes", r"Binghamton/New", r"Binghamton/Fresno State", r"Binghamton/Rochester", r"Binghamton\USMA", r"Biola Chang & Wakashi", r"Biola Eissoh & Calla", r"Biola Leonard & Savi", r"Bishop Guertin", r"Blaine", r"Blake", r"Bloomington", r"Blue Valley North", r"Blue Valley Southwest", r"Blue Valley West Saiedian & Tallavajh", r"BosCol/UniSta", r"Boston College/Binghamton", r"Boston College/Western Connecticut State", r"Boston Debate League", r"Boston Latin", r"Brennan/Munday Munar & Garime", r"Brennan/Solice", r"Bronx Law", r"Bronx Science", r"Brooklyn Independent", r"Brooklyn Technical", r"Brophy", r"Brophy CP", r"Butler", r"Butler Foreman & T", r"CK", r"CK McClatchy", r"CR Washington", r"CRWas B", r"CSU - Northridge/Arizona State", r"CSU Long Beach/Kansas State", r"CSU Northridge/CSU Chico", r"CSU Northridge/Fresno State", r"CSU Northridge/Weber State", r"CUNY/NYU", r"CUNYWestConn", r"CUNY\Rutger", r"CUNY\Rutgers", r"CUNY\Vermon", r"Cabot", r"CadMag", r"Caddo Magnet/Winston Churchill", r"Cal State Fullerton/Binghamton", r"Cal State Fullerton/Fullerton snyder & Hys", r"Cal State Fullerton/Weber State Morton & Mora", r"CalSta", r"Calhoun", r"Camas", r"Canyon Springs", r"Capita", r"Capital", r"CarSch", r"Carmel Valley Independent", r"Carrollton", r"Carrollton Scho", r"Carrollton School of Sacred Heart", r"Carrollton School of the Sacred He", r"Carrollton School of the Sacred Heart", r"Casady", r"Cathedral Prep", r"Cedar Rapids Washington", r"Cent", r"Centennial", r"Central Catholic", r"Chaminade CP", r"Chase/Steiner", r"Chatta", r"Chattahoochee", r"Chicago Independent", r"Chicago Lab Schools", r"Chico\Fullerton", r"City College of San Francisco/San Francisco", r"Clackamas", r"Clarion\UMW", r"Clovis North", r"College Prep", r"Collier/Stanley", r"Columbus", r"Coppel", r"Coppell", r"Copper Hills", r"Cornell/Rochester", r"Coronado", r"Crosby", r"Crowder", r"Cypress Bay", r"Cypress Bay Lance Kotler & Tyler Kot", r"DN", r"Damien", r"Davis", r"Denver Independant", r"Derby Carter & Sall", r"Desert Vista", r"DetCo", r"Dex", r"Doty ", r"Dougherty Valley", r"Dow", r"Dowling", r"Downtown Magnets", r"Dr Izquierdo Health and Science Charter", r"Dulles", r"Dunn", r"Eagan", r"Eagle", r"EasEar", r"East", r"East Kentwood", r"East Palo Alto Phoenix", r"Edgemont", r"Edina", r"El Cerrito Independent", r"Elkins", r"EC", r"Emory/Rochester", r"EmpSta/KanCit", r"Evanston", r"Evanston Twp", r"FigBow\Emory", r"Florida State/Samford", r"Florida/United States Military", r"Fresno State/CSU Northridge", r"Ft. Lauderdale", r"Fresno State/Southwestern", r"Fullerton/Cal State Fullerton", r"GBN", r"GBS", r"GMU/Wayne", r"GPS", r"GSUMinn", r"Garcia/Scott Curry & Dec", r"Garcia/Scott Gordon-Washington & Swan", r"Garcia/Scott Sanders & Hen", r"Georgecink & P", r"Georgetown Day", r"Georgi/Emory", r"Georgia State/Samford", r"Georgia/Georgia State", r"Georgia/Georgia Tech", r"Georgia/Indiana", r"Georgia/Miami", r"Georgia/West Georgia", r"Gig Harbor", r"GleNor", r"GleSou", r"Glenbrook North", r"Glenbrook South", r"Glenbrook South Katie Kenner & SabÃ­n Robe", r"Gonzaga Prep", r"Grapevine", r"Green Valley", r"Greenh", r"Greenhill", r"Groves", r"Gulliver Prep", r"HAIS", r"Hamilton", r"Harker", r"Head Royce", r"Hebron", r"Hendri", r"Hendrickson", r"Henry W Grady", r"Henry W. Grady", r"Highland", r"Highland Park Senior", r"Highland Park TX", r"Hollifield & Ball", r"Homewo", r"Homewood-Flossmoor", r"HouMem", r"Hunter", r"IC City", r"IC West", r"IU\Navy", r"Illinois/GMU", r"Illinois/Nevada Las Vegas", r"Indian/Butler", r"Indian/Samfor", r"Indian/Vander", r"Indiana/Minnesota", r"Indiana/Samford", r"Indiana/Wake Forest", r"Indiana/Wayne", r"Indiana/Wyoming", r"IndianaIowa", r"IndianaMiami", r"Indiana\MoState", r"Indiana\Samford", r"Institute for Collaborative Education", r"Interlake", r"IowCit", r"Iowa City", r"Iowa City West", r"Irvine/San Francisco State", r"Irvine\SFSU", r"Isidore Newman", r"Isidore Newman Rajan Agrawal & Royden Ly", r"JMU/Liberty", r"JMU\Clarion", r"JMU\GMU", r"JamMad/Libert", r"James Logan", r"James Madison/CUNY", r"James Madison/United States Military", r"James Madison/Washington", r"James Madison/West Virginia", r"Jenks", r"Jesuit", r"Jesuit CP", r"JohCar/WaySta", r"Johns Creek", r"Jones CP", r"Juan Diego Catholic", r"June Jordan School for Equity", r"KanCit/Linden Shockley & W", r"KanSta/EmpSta", r"Kapaun Mount Carmel", r"KatTay", r"Katy Taylor", r"Kent", r"Kent Denver", r"Kentucky/Mary Washington", r"Kingwood", r"Kinkai", r"Kinkaid", r"Kipp King Collegiate", r"Knights Independent", r"La Costa Canyon", r"La Salle", r"Lane Tech College Prep H.S.", r"Lansing Sr", r"Leland", r"Leucadia Independent", r"Lex", r"Lexing", r"Lexington", r"Lexington Matthew Tan & Kevin", r"Liberal Arts and Science Academy - LBJ", r"Liberty\Navy", r"Lincoln Prep", r"Little Rock Central", r"Logan", r"Long Beach City", r"Los Alamos", r"Lowell", r"Loyola", r"Lynbrook", r"Magnolia", r"Maine East H.S.", r"Mary Wash\Clarion", r"Mary Washington/Kentucky", r"Mary Washington/Samford", r"McDonogh", r"McDowell", r"McQueen", r"Mead", r"Meadows", r"Mercer", r"MicSta/WaySta Porter & Matmaniv", r"Michigan State/California, Berkeley", r"Mil", r"Mili", r"Millard North", r"Millb", r"Milton", r"Minneapolis South", r"Minneapolis Washburn", r"Minnes/MarWas", r"Minnesota/Augustana College", r"Minnesota/Liberty", r"Minnesota/Mary Washington", r"Minnesota/North Texas", r"Minnesota/Northern Iowa", r"Minnesota/Pittsburgh", r"Minnesota/Wake Forest", r"MisSta/Vander", r"Missouri - Kansas City/UT Dallas", r"Missouri - Kansas City/Wichita State Jaedon Kroger & Luke ", r"Missouri State/Central Florida", r"Missouri State/Clarion", r"MoSt/IU", r"MoState\KSU", r"MonSh", r"Monmou/AriSta", r"Monta Vista", r"Montgomery B", r"Montgomery Bell", r"Mount Vernon Presbyterian", r"Mukwon", r"NV Michigan/Indiana", r"Nashua South", r"Navy/Samford", r"Navy\Liberty", r"Nevada Union", r"Nevada Las VegasCal State Fullerton", r"Nevada Las Vegas/Pepperdine", r"Nevada Las Vegas/Weber State", r"New Trier", r"New/Bingha", r"New/Binghamton", r"New/UniSta", r"NewGMU", r"NewSch/Monmou", r"NewSch/UniSta", r"NewSchool/Columbia", r"NewSchool/KCKCC", r"NewSchool/Liberty", r"NewSchool/Rochester", r"NewSchool/Wyoming", r"Newark Science", r"Newark Tech", r"Niles", r"Niles North", r"Niles West", r"Niles West Eliana Bender & Dylan Chi", r"Niles West Elizabeth Bennett & Nadia Firozab", r"Niles West Patel & Afa", r"North Broward Prep", r"North Broward Prep Nicholas Mancini & Giorgio Rabb", r"North Broward Preparatory", r"North Star Academy", r"North Star Academy CPHS", r"Norcol", r"North", r"North Texas/Houston", r"Northern Iowa/Missouri State", r"NorthernIowa\Minnesota", r"Northridge", r"Northv", r"Northview", r"Northwood Independent", r"Notre Dame", r"Oak Hall", r"Oakland Tech", r"Ohlone", r"Okemos", r"Oregon Episcopal", r"Oregon Episcopal School (OES)", r"Overland Park Southwest", r"Pace", r"Paideia", r"Palo Verde", r"Park City HS", r"Parker", r"Pasadena City Shotwell & Mou", r"Pasadena City Sy Go & Hu", r"Peninsula", r"Phoenix Military", r"Pine Crest Prep", r"Pine Crest Preparatory", r"Pittsburgh Central Catholic", r"Pointe", r"Pointer", r"PolySLO", r"Polytechnic", r"Portage Northern", r"Presentation", r"Puget Sound/Weber State Clare & Alvar", r"Ransom Everglades", r"Reagan", r"Riverside STEM", r"Riverwood", r"Robert McQueen", r"Roches/UVM", r"Rochester/Binghamton", r"Rochester/George Mason", r"Rochester/Oklahoma", r"Rochester/Vermont", r"Rochester/West Virginia", r"Rochester/Western Connecticut State", r"RochesterWCSU", r"Rochester\NYU", r"Rochester\Oklahoma", r"Roosevelt", r"Rosemont", r"Rosemount", r"Rosemount H", r"Roswell", r"Rowland Hall", r"Rowland Hall-St Mark", r"Rowland Hall-St. Mark's", r"Rutger/CUNY", r"Rutger/JamMad", r"Rutgers-Newark/Binghamton", r"Rutgers-Newark/Cal State Fullerton", r"Rutgers-Newark/Rochester", r"Rutgers-Newark/Towson", r"RutgersUniSta", r"Rutgers\Bing", r"S. Eugene H. S.", r"S. Guns", r"SA Harlem North Central", r"SFSU\Irvine", r"SacState Oklahoma ", r"SUNY Broome/United States Military", r"SMU\Minnesota", r"SWC\CSUF", r"Sacramento State/Oklahoma", r"Sacramento State/Southern California", r"Sam Barlow", r"Samfor/IllCol", r"Samford/Georgia", r"Samford/Miami", r"Samford/Missouri State", r"Samford\Indiana", r"Samford\Liberty", r"Samford\SMU", r"San Fran/San Fran State", r"San Francisco State/Irvine", r"San Francisco State/San Francisco", r"San Francisco/San Francisco State", r"SanFra/SanFra", r"Santa Margarita Catholic", r"Seaholm", r"Sharps", r"Silver Creek", r"Skyline", r"Sonoma", r"Southern Maine CC", r"South Eugene", r"SLO", r"Southwestern College/Weber State Rosales & Ze", r"Southwestern/Fullerton", r"St Francis", r"St George's", r"St Martin's Lake & Var", r"St Mary's", r"St Mary's Magee & Pe", r"St Mary's Szafraniec & Jeron", r"St. Croix Prep", r"St. Francis", r"St. Mark's Scho", r"St. Mark's School of Texas", r"St. Vincent De Paul", r"St. Vincent de Paul", r"St.Vin", r"Stratford", r"Strath Haven", r"Stuyvesant", r"Texas/Central Oklahoma", r"Texas/Wyoming", r"Texas\Minnesota", r"Texas\UCO", r"Theodore Roosevelt", r"Thomas Jefferson HSST", r"Thomas Jefferson S&T", r"TCC", r"Traverse City Central", r"Trinity\Kansas", r"Tulsa Union", r"UCF\Kentucky", r"UCO\JCCC", r"UCO\JohCou", r"UCO\KState", r"UCO\Lindenwood", r"UGA/GSU", r"UMKC/KSU State", r"UMKC/KanCit", r"UMKC\UCO", r"UMKC\Wichita", r"UMKC\WichitaState", r"UNI\UCO", r"USMA\CUNY", r"USMA\Navy", r"USMA\New School", r"USMA\WVU", r"USN", r"UT Dallas/Missouri - Kansas City", r"UT San Antonio/Johnson County Community", r"UT San Antonio/Wyoming", r"UVM/New", r"UniSta/JamMad", r"UniSta/WesVir", r"Uniof", r"United States Military/Vermont", r"Univ", r"University", r"University HS - Fresno", r"University HS, Irvine", r"University Prep", r"Vanderbilt/Samford", r"Vandy/Liberty", r"Vermon/CUNY", r"Vermont/Western Connecticut State", r"VermontRochester", r"Vermont\CUNY", r"WDM Valley", r"WFU Totes", r"WVU\Rutgers", r"Wake Forest/Wayne State", r"Wallenberg Traditional", r"Walter Payton CP", r"WashU\KCKCC", r"WashU\Texas", r"Washburn", r"Washburn Rural", r"Washington/James Madison", r"Washington/Minnesota", r"Washington/Nevada Las Vegas", r"Washington/Southern California", r"Washto/JamMad", r"Wayne State/Augustana College", r"WayneIU", r"Wayzat", r"Wayzata", r"Weber State/Arizona State", r"Weber State/Cal State Fullerton", r"Weber State/Southern California", r"Weber StateFresno", r"WesBlo", r"WesVir/Florid", r"WesVir/Roches", r"WesVir/Wilkes", r"West Bloomfield HIgh", r"West DM Valley", r"West Des Moines Valley", r"West Virginia/Binghamton", r"West Virginia/CUNY", r"West Virginia/James Madison", r"West Virginia/New", r"West Virginia/Wayne State", r"WestVirgini\New", r"WestVirginia\New", r"Weste", r"Western Connecticut State/George Mason", r"Western Connecticut State/Miami", r"Westminster", r"Westminster Schools", r"Westminster Schools-Atlanta", r"Westridge", r"Westwo", r"Westwood", r"Wheeler", r"WhiCol/PugSou", r"Whitman College/Washington", r"Whitney M. Young Magnet", r"Whitney Yo", r"Whitney Young", r"Whitney Young Catherine Jacob & Dorothy Tara", r"Wilson Senior", r"Winston Churchill", r"Wisconsin- Madison/Georgia State", r"Woodlands", r"Woodlands Independent", r"Woodside", r"Woodw", r"Woodward", r"Wylie E. Groves", r"Wylie E. Groves Boarman & Rajagopa", r"Wyoming/Sacramento State", r"Wyoming/Weber State", r"Wyoming\Indiana", r"Wyoming\UNLV", ]

'''csv_file = open('raw_dict_source.csv', encoding="utf-8")
reader = csv.reader(csv_file)

included_list = []
excluded_list = []

for row in reader:
  for entry in row:
    if len(entry) > 0:
      if entry in school_dict:
        included_list.append(entry)
      else:
        excluded_list.append(entry)


print(len(included_list))
print(excluded_list)

if 'ASU' in school_dict:
  print("It's in there.")

print('Length of Ignore list = ' + str(len(ignore_list)))
print('Length of counting dictionary = ' + str(len(counting_dict)))

for key in counting_dict.keys():
  if key.startswith('ASU'):
    print(key)

for key in counting_dict.keys():
  print(key)'''